### ISSUE TITLE
Module import order matters, but shouldn't.

### ISSUE THREAD

**Issue by lengau** [canonical/craft-providers#262]
This code:

```python
from craft_providers.actions import snap_installer
from craft_providers.bases import get_base_alias, get_base_from_alias
```

fails:

```
$ python3.8 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from craft_providers.actions.snap_installer import Snap
  File "/home/lengau/Code/craft-application/.tox/test-py38/lib/python3.8/site-packages/craft_providers/actions/snap_installer.py", line 34, in <module>
    from craft_providers.bases.instance_config import InstanceConfiguration
  File "/home/lengau/Code/craft-application/.tox/test-py38/lib/python3.8/site-packages/craft_providers/bases/__init__.py", line 28, in <module>
    from . import centos
  File "/home/lengau/Code/craft-application/.tox/test-py38/lib/python3.8/site-packages/craft_providers/bases/centos.py", line 35, in <module>
    from craft_providers.actions.snap_installer import Snap, SnapInstallationError
ImportError: cannot import name 'Snap' from partially initialized module 'craft_providers.actions.snap_installer' (most likely due to a circular import) (/home/lengau/Code/craft-application/.tox/test-py38/lib/python3.8/site-packages/craft_providers/actions/snap_installer.py)
```

But swapping the import order:

```python
from craft_providers.bases import get_base_alias, get_base_from_alias
from craft_providers.actions import snap_installer
```

succeeds.

**Comment by tigarmo** [comment]
@lengau I think you put the same import order twice

**Comment by lengau** [comment]
@tigarmo Thanks - fixed!

**Comment by mr-cal** [comment]
Fixed in #274
