### ISSUE TITLE
Error when packing a charm with missing group name

### ISSUE THREAD

**Issue by knkski** [canonical/craft-providers#79]
I tried packing a charm, and it failed with this message:

    charmcraft internal error! KeyError: 'getgrgid(): gid not found: 135' (full execution logs in /home/knkski/snap/charmcraft/common/charmcraft-log-ty_na9vr)

Opening that file, I see this traceback:

```
Traceback (most recent call last):
  File "/snap/charmcraft/698/lib/charmcraft/main.py", line 367, in main
    retcode = dispatcher.run()
  File "/snap/charmcraft/698/lib/charmcraft/main.py", line 351, in run
    return self.command.run(self.parsed_args)
  File "/snap/charmcraft/698/lib/charmcraft/commands/pack.py", line 140, in run
    self._pack_charm(parsed_args)
  File "/snap/charmcraft/698/lib/charmcraft/commands/pack.py", line 174, in _pack_charm
    charms = builder.run(parsed_args.bases_index, destructive_mode=build_args.destructive_mode)
  File "/snap/charmcraft/698/lib/charmcraft/commands/build.py", line 361, in run
    self.provider.ensure_provider_is_available()
  File "/snap/charmcraft/698/lib/charmcraft/providers/_lxd.py", line 128, in ensure_provider_is_available
    lxd.ensure_lxd_is_ready()
  File "/snap/charmcraft/698/lib/craft_providers/lxd/installer.py", line 138, in ensure_lxd_is_ready
    if not is_user_permitted():
  File "/snap/charmcraft/698/lib/craft_providers/lxd/installer.py", line 110, in is_user_permitted`
    return os.geteuid() == 0 or any(
  File "/snap/charmcraft/698/lib/craft_providers/lxd/installer.py", line 111, in <genexpr>
    grp.getgrgid(g).gr_name == "lxd" for g in os.getgroups()
KeyError: 'getgrgid(): gid not found: 135'
```

Poking around, I can replicate this behavior. `id -nG` shows various group names, but also includes `id: cannot find name for group ID 135\n135`. The Python console shows this:

```python
>>> [grp.getgrgid(g).gr_name for g in os.getgroups()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
KeyError: 'getgrgid(): gid not found: 135'
```

I would guess that this is due to me cleaning up my system today by purging lots of old apt packages.

**Comment by mr-cal** [comment]
Fixed in https://github.com/canonical/craft-providers/pull/105
